[package]
name = "catalyst"
version = "0.0.1"
edition = "2024"

[dependencies]
pulldown-cmark = "0.13.0"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4.5.53", features = ["derive"] }
chrono = "0.4"
notify = "8.1.0"
walkdir = "2.5.0"